# # docker-compose.yml
redis:
  image: redis
  container_name: cache
  ports:
    - 6379:6379
  # expose:
  #   - 6379
app:
  links:
    - redis
  build: ./
  volumes:
    - ./:/var/www/app
  ports:
    - 3000:3000
  environment:
    - REDIS_URL=redis://cache
    - NODE_ENV=production
    - PORT=3000
  command: sh -c 'npm i && npm run start'